
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    password: 911368169umid
    username: postgres
    url: jdbc:postgresql://localhost:5432/apelsin
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: /api
debug: true
server:
  port: 3047
  servlet:
    context-path: /api



